### ISSUE TITLE
Low Performance in Demo Scene

### ISSUE THREAD

**Issue by EuanHoll** [GabrielMusat/react-stl-viewer#1]
When using the demo scene on multiple devices it provides a choppy low framerate, especially on version 2+. Brave claims `system (self)` uses the most time (~400ms).

The fast machine's specs : 
- Ryzen 3600
- GTX 1070
- 16GB Ram

**Comment by GabrielMusat** [comment]
Testing the demo scene (README.md example) gives me a solid 60 fps in this old laptop:

Intel® Core™ i5-3210M CPU
Intel® HD Graphics 4000 (IVB GT2) 
8GB Ram

Tested on Chrome and Firefox.
Could you provide more detailed steps to reproduce? browser versions you have tested, OS, etc...

Does the same thing happen if you disable the shadows?

**Comment by GabrielMusat** [comment]
Testing the scene in Brave gives me very good performance (tested on 1.33.106). 

This is more likely an issue in webgl2 and Brave compatibility. Also latests versions of three.js seem to be causing problems in Brave (#https://github.com/mrdoob/three.js/issues/22676). 
In Brave search bar, you can write _brave://gpu/_ and it will tell you the graphics feature status.

In any case, there is nothing we can do in this library as it doesn't control the underlying rendering engine.

**Comment by EuanHoll** [comment]
So apparently I'm running on software only so it makes sense about the lag. So it is probably a combination between three.js and my brave settings.

```
Canvas: Software only, hardware acceleration unavailable
Canvas out-of-process rasterization: Disabled
Compositing: Software only. Hardware acceleration disabled
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Disabled
OpenGL: Disabled
Rasterization: Software only. Hardware acceleration disabled
Raw Draw: Disabled
Skia Renderer: Enabled
Video Decode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Software only, hardware acceleration unavailable
WebGL2: Software only, hardware acceleration unavailable
```
